# Main Application Configuration
app:
  name: "iPDF - Multimodal PDF Assistant"
  version: "2.0.0"
  description: "100% FREE PDF chat with RAG"
  max_upload_size_mb: 50

# Logging Configuration
logging:
  level: INFO
  format: "[%(asctime)s] %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_rotation:
    max_bytes: 10485760  # 10MB
    backup_count: 5

# Document Processing
document:
  extraction_strategy: "hi_res"
  extract_images: true
  extract_tables: true
  infer_table_structure: true
  chunk_size: 1000
  chunk_overlap: 200
  enable_ocr: true
  ocr_dpi: 100

# Embeddings (FREE via Ollama)
embeddings:
  provider: "ollama"
  model: "nomic-embed-text"
  dimensions: 768
  base_url: "http://localhost:11434"

# Vector Store (FREE - Qdrant Cloud)
vectorstore:
  provider: "qdrant"
  collection_name: "ipdf_multimodal"
  distance_metric: "COSINE"
  search_limit: 5
  vector_size: 768

# LLM Configuration (FREE via Ollama)
llm:
  provider: "ollama"
  model: "llama3.2"
  temperature: 0.1
  max_tokens: 2048
  base_url: "http://localhost:11434"

# UI Settings
ui:
  page_title: "iPDF - Chat with PDFs"
  page_icon: "📄"
  layout: "wide"
  sidebar_state: "expanded"
  pdf_viewer_height: 800
  chat_height: 600
  theme:
    primary_color: "#1f77b4"
    background_color: "#ffffff"
    text_color: "#262730"
