# Available Models Configuration (All FREE via Ollama)

# LLM Models
llm_models:
  - name: "Llama 3.2 (3B)"
    model_id: "llama3.2"
    provider: "ollama"
    size: "3B parameters"
    description: "Fast, efficient, great for chat"
    recommended: true
    
  - name: "Llama 3.2 (1B)"
    model_id: "llama3.2:1b"
    provider: "ollama"
    size: "1B parameters"
    description: "Ultra-fast, lightweight"
    recommended: false
    
  - name: "Mistral (7B)"
    model_id: "mistral"
    provider: "ollama"
    size: "7B parameters"
    description: "Powerful, detailed responses"
    recommended: false

# Embedding Models
embedding_models:
  - name: "Nomic Embed Text"
    model_id: "nomic-embed-text"
    provider: "ollama"
    dimensions: 768
    description: "Best for semantic search"
    recommended: true
    
  - name: "All MiniLM L6 v2"
    model_id: "all-minilm:l6-v2"
    provider: "ollama"
    dimensions: 384
    description: "Lightweight, fast"
    recommended: false
